main: login.cgi bulletinz.cgi videoz.cgi studyz.cgi swapz.cgi reg.cgi greg.cgi tourist.cgi bulletinzz.cgi bulletiny.cgi
login.cgi:login.cc
	g++ $^ -o $@ -lmysqlcppconn
bulletinz.cgi:bulletinz.cc
	g++ $^ -o $@ -lmysqlcppconn
bulletinzz.cgi:bulletinzz.cc
	g++ $^ -o $@ -lmysqlcppconn
bulletiny.cgi:bulletiny.cc
	g++ $^ -o $@ -lmysqlcppconn
videoz.cgi:videoz.cc
	g++ $^ -o $@ -lmysqlcppconn
tourist.cgi:tourist.cc
	g++ $^ -o $@ -lmysqlcppconn
studyz.cgi:studyz.cc
	g++ $^ -o $@ -lmysqlcppconn
swapz.cgi:swapz.cc
	g++ $^ -o $@ -lmysqlcppconn
reg.cgi:reg.cc
	g++ $^ -o $@ -lmysqlcppconn
greg.cgi:greg.cc
	g++ $^ -o $@ -lmysqlcppconn



